### ISSUE TITLE
Inaccurate GPU information reporting

### ISSUE THREAD

**Issue by kcgthb** [CLIP-HPC/SlurmCommander#5]
In the "Cluster" tab, GPU information seems to be incorrectly reported.

For instance, node `sh03-12n09` has 4 GPUs, 3 being allocated, and the TUI reports GPUAvail: 0, GPUTotal: 3

![image](https://user-images.githubusercontent.com/186807/208764450-1d41c237-ee71-4d07-b841-4cb370ea4532.png)

```
# scontrol show node sh03-12n09  | grep gres
   CfgTRES=cpu=32,mem=250G,billing=154,gres/gpu=4
   AllocTRES=cpu=15,mem=48G,gres/gpu=3
```

**Comment by pja237** [comment]
@timeu Can you take a look at this please?

**Comment by pja237** [comment]
Gpu reporting is consistently wrong for all your gpu nodes?
Could you run `sinfo --json -a`, and just find in json for that node these lines:
```
       "gres": "",
       "gres_drained": "N\/A",
       "gres_used": "gpu:0",
```
(or any other gpu node that you see wrongly reported)

**Comment by kcgthb** [comment]
I didn't check them all, but the vast majority of our GPU nodes information is not reported correctly, indeed.

Here's the direct JSON output:
```
$ sinfo --json -a | jq '.nodes[] | select(.hostname=="sh03-12n09") | with_entries( select(.key|contains("gres")) )'
{
  "gres": "gpu:4(S:0-1)",
  "gres_drained": "N/A",
  "gres_used": "gpu:(null):4(IDX:0-3)"
}
```

**Comment by pja237** [comment]
Hey, thank you for the JSON, that clarified everything 👍 
Can you just double check the build on your site that it's green to go? (looks good on my side)
https://github.com/CLIP-HPC/SlurmCommander/suites/10013437387/artifacts/486463027

**Comment by pja237** [comment]
I'll merge the PR and release, just reopen if you find something missing.

**Comment by erichweiler** [comment]
I think this maybe the same (but somehow different?) issue...  But I am also seeing GPUs being reported incorrectly.
<img width="843" alt="cluster" src="https://github.com/CLIP-HPC/SlurmCommander/assets/20846787/8e91b0f5-7ea4-4bbd-aac0-6f5049cbe5e8">
 I should note that we have a cluster with several types of GPUs, and have labeled them as such.  Maybe that's making something break?

```
# sinfo --json -a | jq '.nodes[] | select(.hostname=="phoenix-01") | with_entries( select(.key|contains("gres")) )'
{
  "gres": "gpu:A5500:8",
  "gres_drained": "N/A",
  "gres_used": "gpu:A5500:0(IDX:N/A)"
}

# scontrol show node phoenix-01  | grep Gres
   Gres=gpu:A5500:8

```

You can see in the graphic that one node is showing "-8" GPUs available, presumably because 8 GPUs are in use on that node:

```
# sinfo --json -a | jq '.nodes[] | select(.hostname=="phoenix-02") | with_entries( select(.key|contains("gres")) )'
{
  "gres": "gpu:A5500:8",
  "gres_drained": "N/A",
  "gres_used": "gpu:A5500:8(IDX:0-7)"
}
```
Either something is getting lost in translation, or maybe slurm is reporting GPUs incorrectly?

```
# scontrol show node phoenix-02
NodeName=phoenix-02 Arch=x86_64 CoresPerSocket=32
   CPUAlloc=98 CPUTot=128 CPULoad=11.56
   AvailableFeatures=(null)
   ActiveFeatures=(null)
   Gres=gpu:A5500:8
   NodeAddr=phoenix-02 NodeHostName=phoenix-02 Version=21.08.5
   OS=Linux 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023
   RealMemory=1996800 AllocMem=590682 FreeMem=1979305 Sockets=2 Boards=1
   State=MIXED ThreadsPerCore=2 TmpDisk=0 Weight=1000 Owner=N/A MCS_label=N/A
   Partitions=main
   BootTime=2023-05-01T17:08:32 SlurmdStartTime=2023-05-05T12:05:06
   LastBusyTime=2023-05-17T13:13:35
   CfgTRES=cpu=128,mem=1950G,billing=128
   AllocTRES=cpu=98,mem=590682M
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s
```
I am using Slurm Commander v1.0.5:

Version: v1.0.5
Build commit hash: 8bf029f6be143194742b0469d635399c5805c06a

Using Slurm 21.08.5 on Ubuntu 22.04.02.

Awesome tool BTW!!
